spring:
  main:
    web-environment: false

flickr:
  apiKey: 7702646706f40b6c735fec76b0dd1cb5
  secret: 5a0bf605f48d7d6c
  photosPerPage: 1000

google:
  apiKey: AIzaSyBHDy8UYJvgOcYEYuVrr5YiHjdpqEYmK8w

zeromq:
  topic:
    findRoutes:
      envelope: FIND_ROUTES_TASK
      address: tcp://*:5563
      ioThreads: 1
    saveRoutes:
      envelope: SAVE_ROUTES_TASK
      address: tcp://*:5564
      ioThreads: 1